import { AppDefinition, DashboardItem } from './types';

export const DASHBOARD_ITEMS: DashboardItem[] = [
  {
    id: 'plex',
    title: 'Plex',
    subtitle: 'Streaming av filmer & serier',
    icon: '🎬',
    status: 'active',
    type: 'link',
    target: '#',
  },
  {
    id: 'projects',
    title: 'Alla Projekt',
    subtitle: 'Källkod från GitHub',
    icon: '🌐',
    status: 'active',
    type: 'page',
    target: 'projects',
  },
  {
    id: 'library',
    title: 'Appbiblioteket',
    subtitle: 'Mina egna webbappar',
    icon: '📱',
    status: 'active',
    type: 'page',
    target: 'library',
  },
  {
    id: 'mobile',
    title: 'Mobilappar',
    subtitle: 'Android-appar att ladda ner',
    icon: '📲',
    status: 'active',
    type: 'link',
    target: '#',
  },
  {
    id: 'control',
    title: 'AI Funktioner',
    subtitle: 'Dashboard för AI-prompter, assistenter och verktyg',
    icon: '🧠',
    status: 'active',
    type: 'page',
    target: 'ai-features',
  },
  {
    id: 'games',
    title: 'Spelbiblioteket',
    subtitle: 'Egenskapade webbspel',
    icon: '🎮',
    status: 'active',
    type: 'page',
    target: 'games',
  },
];

export const GAMES: AppDefinition[] = [
  {
    id: 'retro-racer',
    title: 'Retro Racer',
    description: 'Ett snabbt racingspel med 8-bitars grafik och synthwave-musik.',
    icon: '🏎️',
    category: 'Spel',
    tags: ['Canvas', 'Retro', 'Arcade'],
    imageSeed: 'racing-game',
    status: 'active',
    createdAt: '2024-03-15T10:00:00Z',
    type: 'Game',
  },
  {
    id: 'space-invaders',
    title: 'Galaxy Defender',
    description: 'Försvara jorden mot invaderande utomjordingar i detta klassiska arkadspel.',
    icon: '🚀',
    category: 'Spel',
    tags: ['JavaScript', 'Space', 'Shooter'],
    imageSeed: 'space-battle',
    status: 'active',
    createdAt: '2024-03-10T14:30:00Z',
    type: 'Game',
  },
  {
    id: 'neon-puzzle',
    title: 'Neon Blocks',
    description: 'Ett beroendeframkallande pusselspel med lysande färger och utmanande nivåer.',
    icon: '🧩',
    category: 'Spel',
    tags: ['Puzzle', 'Neon', 'Logic'],
    imageSeed: 'puzzle-blocks',
    status: 'active',
    createdAt: '2024-03-20T09:15:00Z',
    type: 'Game',
  },
];

export const APPS: AppDefinition[] = [
  {
    id: 'viktapp',
    title: 'Viktapp',
    description: 'Spåra din viktnedgång och Wegovy-injektioner. Se BMI-mätare, progress och statistik för din hälsoresa.',
    icon: '💉',
    category: 'Hälsa',
    tags: ['Next.js', 'Directus', 'Hälsa'],
    imageSeed: 'fitness',
    status: 'active',
    createdAt: '2024-01-05T08:00:00Z',
    type: 'Web App',
  },
  {
    id: 'bilkostnad',
    title: 'Bilkostnad',
    description: 'Håll koll på alla bilkostnader – bränsle, service, lagning, försäkring, trängselskatt och besiktning.',
    icon: '⛽',
    category: 'Ekonomi',
    tags: ['React', 'Directus', 'PWA', 'Ekonomi'],
    imageSeed: 'car',
    status: 'active',
    createdAt: '2024-01-12T11:20:00Z',
    type: 'PWA',
  },
  {
    id: 'somndagbok',
    title: 'Sömndagbok',
    description: 'Logga sömn och CPAP-data varje natt. Läggdags, uppstigningstid, sömnkvalitet och AHI.',
    icon: '💤',
    category: 'Hälsa',
    tags: ['React', 'Directus', 'CPAP', 'Hälsa'],
    imageSeed: 'sleep',
    status: 'active',
    createdAt: '2024-01-20T22:45:00Z',
    type: 'Web App',
  },
  {
    id: 'balansa',
    title: 'Balansa',
    description: 'Personlig budget-app. Registrera inkomster och utgifter per kategori, sätt sparmål och utgifter.',
    icon: '📊',
    category: 'Ekonomi',
    tags: ['Next.js', 'Finance'],
    imageSeed: 'money',
    status: 'active',
    createdAt: '2024-02-01T15:30:00Z',
    type: 'Web App',
  },
  {
    id: 'padel',
    title: 'Padel-Dashboard',
    description: 'Personlig padel-app. Logga matcher med vinn/förlust, hantera racket, kör Americano.',
    icon: '🎾',
    category: 'Sport',
    tags: ['React', 'Sports'],
    imageSeed: 'padel',
    status: 'active',
    createdAt: '2024-02-10T10:00:00Z',
    type: 'Web App',
  },
  {
    id: 'surd',
    title: 'IK Surd Padel',
    description: 'Padel-app för IK Surds padelsektionen. Träningar, tävlingar, matchbokning, forum.',
    icon: '🏆',
    category: 'Sport',
    tags: ['React', 'Community'],
    imageSeed: 'tournament',
    status: 'active',
    createdAt: '2024-02-15T09:00:00Z',
    type: 'Web App',
  },
  {
    id: 'filmtextning',
    title: 'Filmtextning',
    description: 'AI-driven app för att skapa textremsor till videor. Automatisk transkribering med OpenAI Whisper.',
    icon: '🎬',
    category: 'Kreativt',
    tags: ['OpenAI Whisper', 'Claude AI', 'Kreativt'],
    imageSeed: 'video-editing',
    status: 'active',
    createdAt: '2024-02-20T14:00:00Z',
    type: 'Web App',
  },
  {
    id: 'musikverkstan',
    title: 'Musikverkstan',
    description: 'AI-musikstudio för att skriva texter, generera musik, lägga till röst och skapa omslag.',
    icon: '🎵',
    category: 'Kreativt',
    tags: ['Next.js', 'OpenAI', 'Suno', 'Kreativt'],
    imageSeed: 'music-studio',
    status: 'active',
    createdAt: '2024-02-25T16:30:00Z',
    type: 'Web App',
  },
  {
    id: 'golfapp',
    title: 'Golfapp 2.0',
    description: 'Spåra golfrundor, hantera din bag, beräkna handikapp och se din utveckling över tid.',
    icon: '⛳',
    category: 'Sport',
    tags: ['React', 'Directus', 'PWA', 'Sport'],
    imageSeed: 'golf',
    status: 'active',
    createdAt: '2024-03-01T10:00:00Z',
    type: 'PWA',
  },
  {
    id: 'larareai',
    title: 'LärareAI',
    description: 'En AI-driven lärarapp som hjälper elever och lärare med undervisning, frågor och pedagogiskt stöd.',
    icon: '🤖',
    category: 'Utbildning',
    tags: ['Claude AI', 'Web App', 'Utbildning'],
    imageSeed: 'education-ai',
    status: 'active',
    createdAt: '2024-03-05T08:00:00Z',
    type: 'Web App',
  },
  {
    id: 'kalorikollen',
    title: 'Kalorikollen',
    description: 'En smart app designad för att logga mat, räkna kalorier och hålla koll på nutritionen dagligen.',
    icon: '🔥',
    category: 'Hälsa',
    tags: ['React', 'Node.js', 'Hälsa'],
    imageSeed: 'healthy-food',
    status: 'active',
    createdAt: '2024-03-08T11:20:00Z',
    type: 'Web App',
  },
  {
    id: 'jarl',
    title: 'Jarl',
    description: 'En föräldrarapp med uppmuntran till sina barn.',
    icon: '⭐',
    category: 'Familj',
    tags: ['Web App', 'Familj'],
    imageSeed: 'family',
    status: 'active',
    createdAt: '2024-03-10T15:30:00Z',
    type: 'Web App',
  },
  {
    id: 'teckensprakai',
    title: 'Teckenspråks AI',
    description: 'AI-drivet klassrum för teckenspråk. Interaktiva lektioner med AI-stöd som hjälper elever lära sig.',
    icon: '🤟',
    category: 'Utbildning',
    tags: ['Node.js', 'OpenAI', 'Utbildning'],
    imageSeed: 'sign-language',
    status: 'active',
    createdAt: '2024-03-12T10:00:00Z',
    type: 'Web App',
  },
  {
    id: 'skuld',
    title: 'Skuld',
    description: 'Håll koll på gemensamma skulder och återbetalningar med en partner. Lägg till utgifter och följ historiken.',
    icon: '💸',
    category: 'Ekonomi',
    tags: ['Next.js', 'Directus', 'Ekonomi'],
    imageSeed: 'debt-tracking',
    status: 'active',
    createdAt: '2024-03-15T09:00:00Z',
    type: 'Web App',
  },
  {
    id: 'rabiff',
    title: 'Råbiff-rankingen',
    description: 'Betygsätt och håll koll på dina bästa råbiffar. Lägg till bilder, plats och poäng.',
    icon: '🥩',
    category: 'Mat',
    tags: ['React', 'Directus', 'PWA', 'Mat'],
    imageSeed: 'steak-tartare',
    status: 'active',
    createdAt: '2024-03-18T14:00:00Z',
    type: 'PWA',
  },
  {
    id: 'hundvakt',
    title: 'Hundvakt CRM',
    description: 'Ett komplett boknings- och kundregister för hundvaktsverksamhet. Hantera hundar, kunder och kalender.',
    icon: '🐾',
    category: 'Företag',
    tags: ['Vite', 'Firebase', 'Företag'],
    imageSeed: 'dog-walking',
    status: 'active',
    createdAt: '2024-03-20T16:30:00Z',
    type: 'Web App',
  },
];
