import { AppDefinition, DashboardItem } from './types';

export const DASHBOARD_ITEMS: DashboardItem[] = [
  {
    id: 'plex',
    title: 'Plex',
    subtitle: 'Streaming av filmer & serier',
    icon: '🎬',
    status: 'active',
    type: 'link',
    target: '#',
  },
  {
    id: 'projects',
    title: 'Alla Projekt',
    subtitle: 'Källkod från GitHub',
    icon: '🌐',
    status: 'active',
    type: 'page',
    target: 'projects',
  },
  {
    id: 'library',
    title: 'Appbiblioteket',
    subtitle: 'Mina egna webbappar',
    icon: '📱',
    status: 'active',
    type: 'page',
    target: 'library',
  },
  {
    id: 'mobile',
    title: 'Mobilappar',
    subtitle: 'Android-appar att ladda ner',
    icon: '📲',
    status: 'active',
    type: 'link',
    target: '#',
  },
  {
    id: 'control',
    title: 'Alex kontrollpanel',
    subtitle: 'Dashboard för projekt, appar och AI-prompter',
    icon: '🧠',
    status: 'active',
    type: 'link',
    target: '#',
  },
  {
    id: 'games',
    title: 'Spelarkivet',
    subtitle: 'Egenskapade webbspel',
    icon: '🎮',
    status: 'active',
    type: 'link',
    target: '#',
  },
];

export const APPS: AppDefinition[] = [
  {
    id: 'viktapp',
    title: 'Viktapp',
    description: 'Spåra din viktnedgång och Wegovy-injektioner. Se BMI-mätare, progress och statistik för din hälsoresa.',
    icon: '💉',
    category: 'Hälsa',
    tags: ['Next.js', 'Directus', 'Hälsa'],
    imageSeed: 'fitness',
    status: 'active',
  },
  {
    id: 'bilkostnad',
    title: 'Bilkostnad',
    description: 'Håll koll på alla bilkostnader – bränsle, service, lagning, försäkring, trängselskatt och besiktning.',
    icon: '⛽',
    category: 'Ekonomi',
    tags: ['React', 'Directus', 'PWA', 'Ekonomi'],
    imageSeed: 'car',
    status: 'active',
  },
  {
    id: 'somndagbok',
    title: 'Sömndagbok',
    description: 'Logga sömn och CPAP-data varje natt. Läggdags, uppstigningstid, sömnkvalitet och AHI.',
    icon: '💤',
    category: 'Hälsa',
    tags: ['React', 'Directus', 'CPAP', 'Hälsa'],
    imageSeed: 'sleep',
    status: 'active',
  },
  {
    id: 'balansa',
    title: 'Balansa',
    description: 'Personlig budget-app. Registrera inkomster och utgifter per kategori, sätt sparmål och utgifter.',
    icon: '📊',
    category: 'Ekonomi',
    tags: ['Next.js', 'Finance'],
    imageSeed: 'money',
    status: 'active',
  },
  {
    id: 'padel',
    title: 'Padel-Dashboard',
    description: 'Personlig padel-app. Logga matcher med vinn/förlust, hantera racket, kör Americano.',
    icon: '🎾',
    category: 'Sport',
    tags: ['React', 'Sports'],
    imageSeed: 'padel',
    status: 'active',
  },
  {
    id: 'surd',
    title: 'IK Surd Padel',
    description: 'Padel-app för IK Surds padelsektionen. Träningar, tävlingar, matchbokning, forum.',
    icon: '🏆',
    category: 'Sport',
    tags: ['React', 'Community'],
    imageSeed: 'tournament',
    status: 'active',
  },
];
