import { AppDefinition, DashboardItem, MobileAppDefinition } from './types';

export const DASHBOARD_ITEMS: DashboardItem[] = [
  {
    id: 'plex',
    title: 'Plex',
    subtitle: 'Streaming av filmer & serier',
    icon: '🎬',
    banner: "linear-gradient(135deg, #1f1300, #e5a00d)",
    bannerEmoji: '🎬',
    status: 'active',
    type: 'link',
    target: 'https://alexcloud.se:32400/web',
  },
  {
    id: 'projects',
    title: 'Alla Projekt',
    subtitle: 'Källkod från GitHub',
    icon: '🌐',
    banner: "linear-gradient(135deg, #0d1117, #238636)",
    bannerEmoji: '🌐',
    status: 'active',
    type: 'page',
    target: 'projects',
  },
  {
    id: 'library',
    title: 'Appbiblioteket',
    subtitle: 'Mina egna webbappar',
    icon: '📱',
    banner: "linear-gradient(135deg, #0a2a4a, #4f9cff)",
    bannerEmoji: '📱',
    status: 'active',
    type: 'page',
    target: 'library',
  },
  {
    id: 'mobile',
    title: 'Mobilappar',
    subtitle: 'Android-appar att ladda ner',
    icon: '📲',
    banner: "linear-gradient(135deg, #073042, #3ddc84)",
    bannerEmoji: '📲',
    status: 'active',
    type: 'page',
    target: 'mobile',
  },
  {
    id: 'control',
    title: 'AI Funktioner',
    subtitle: 'Dashboard för AI-prompter, assistenter och verktyg',
    icon: '🧠',
    banner: "linear-gradient(135deg, #1a0b2e, #7c3aed)",
    bannerEmoji: '🧠',
    status: 'active',
    type: 'page',
    target: 'ai-features',
  },
  {
    id: 'games',
    title: 'Spelbiblioteket',
    subtitle: 'Egenskapade webbspel',
    icon: '🎮',
    banner: "linear-gradient(135deg, #030009, #00f5ff)",
    bannerEmoji: '🎮',
    status: 'active',
    type: 'page',
    target: 'games',
  },
  {
    id: 'private',
    title: 'Övriga appar',
    subtitle: 'Personliga appar – lösenordsskyddat',
    icon: '🔒',
    banner: "linear-gradient(135deg, #1f1147, #3b0764)",
    bannerEmoji: '🔒',
    status: 'active',
    type: 'page',
    target: 'private',
  },
  {
    id: 'shared',
    title: 'Andras appar',
    subtitle: 'Appar andra delat – t.ex. på GitHub',
    icon: '🤝',
    banner: "linear-gradient(135deg, #0d1117, #1f6feb)",
    bannerEmoji: '🌍',
    status: 'active',
    type: 'page',
    target: 'shared',
  },
  {
    id: 'system',
    title: 'Systemappar',
    subtitle: 'Serververktyg – lösenordsskyddat',
    icon: '⚙️',
    banner: "linear-gradient(135deg, #111827, #374151)",
    bannerEmoji: '⚙️',
    status: 'active',
    type: 'page',
    target: 'system',
  },
];

// Mobilappar – flyttade från gamla alexcloud.se/mobile.html (2026-06-11).
// APK-filer ligger i ./downloads och serveras av server.ts under /downloads.
export const MOBILE_APPS: MobileAppDefinition[] = [
  {
    id: 'kalorikollen-mobil',
    bannerImage: 'https://databasen.alexcloud.se/assets/434fdead-07cd-45d8-af3d-289eae380576?width=800&quality=80',
    title: 'Kalorikollen',
    description: 'Mobilversion av den populära kaloriräknaren. Logga måltider på språng, skanna streckkoder, få snabba näringsanalyser och synka med webbversionen för sömlös uppföljning.',
    icon: '🔥',
    banner: 'linear-gradient(135deg, #FF6B6B, #556270)',
    bannerEmoji: '🥗',
    tags: ['React Native', 'Expo', 'Hälsa'],
    kind: 'APK',
    status: 'coming-soon',
  },
  {
    id: 'rabiff-mobil',
    bannerImage: 'https://databasen.alexcloud.se/assets/334737bd-7990-42f0-9c60-d8de89a3179b?width=800&quality=80',
    title: 'Råbiff',
    description: 'Den ultimata appen för råbiffsentusiaster! Hitta och betygsätta Sveriges bästa råbiff, dela dina upptäckter med bilder, spara favoriter och utforska nya ställen baserat på recensioner.',
    icon: '⭐',
    banner: 'linear-gradient(135deg, #8B4513, #D2691E)',
    bannerEmoji: '🥩',
    tags: ['React Native', 'Supabase', 'Mat & Dryck'],
    kind: 'APK',
    status: 'coming-soon',
  },
  {
    id: 'golfapp2-pwa',
    bannerImage: 'https://databasen.alexcloud.se/assets/bde64d80-4991-4c16-8c24-97b2c91244e1?width=800&quality=80',
    title: 'Golfapp 2.0',
    description: 'Ny version av golfappen – spåra rundor, hantera din bag, beräkna handikapp och se din utveckling. Ingen installation krävs, fungerar som en riktig app direkt i mobilen.',
    icon: '🏌️',
    banner: 'linear-gradient(135deg, #0D2818, #1a5c34)',
    bannerEmoji: '⛳',
    tags: ['React', 'Directus', 'Sport'],
    kind: 'PWA',
    status: 'active',
    url: 'https://golfapp2.alexcloud.se',
  },
  {
    id: 'viktapp-pwa',
    bannerImage: 'https://databasen.alexcloud.se/assets/c568c953-5da3-4c37-8872-9bf325e0a60f?width=800&quality=80',
    title: 'Vikttapp',
    description: 'Spåra din viktnedgång och Wegovy-injektioner. Se BMI-mätare, progress och statistik för din hälsoresa. Fungerar som en app direkt i mobilen.',
    icon: '💉',
    banner: 'linear-gradient(135deg, #0ea5e9, #38bdf8)',
    bannerEmoji: '⚖️',
    tags: ['Next.js', 'Directus', 'Hälsa'],
    kind: 'PWA',
    status: 'active',
    url: 'https://viktapp.alexcloud.se/dashboard',
  },
  {
    id: 'golf-scorecard',
    bannerImage: 'https://databasen.alexcloud.se/assets/644985e0-82f7-4890-9eac-ef03b42709f9?width=800&quality=80',
    title: 'Golf Scorecard',
    description: 'Digitalt scorekort för att spåra golfrundor, slaglängder och beräkna handikapp. Integrerad med databas för att spara historik och utveckling per bana.',
    icon: '🏌️',
    banner: 'linear-gradient(135deg, #11998e, #38ef7d)',
    bannerEmoji: '⛳',
    tags: ['React Native', 'Expo', 'Sport'],
    kind: 'APK',
    status: 'active',
    url: '/downloads/golfappen.apk',
    fileSize: '~76 MB',
  },
];

// Appar som andra delat med sig av (t.ex. GitHub). url pekar på live-appen eller repot.
export const SHARED_APPS: AppDefinition[] = [
  {
    id: 'owl-creek-radio',
    bannerImage: 'https://databasen.alexcloud.se/assets/6c1dc642-3568-42ec-a502-8bbb6b8eb896?width=800&quality=80',
    title: 'Owl Creek Radio',
    description: 'Personlig AI-radiostation (KOWL 99.3) som sänder i webbläsaren från dimmiga Glassfall. En AI-programledare skapar nyheter, väder, prat och musik i en simulerad livesändning. Delad app från GitHub (fltman).',
    icon: '🦉',
    banner: "linear-gradient(135deg, #0a1410, #1c3a2e)",
    bannerEmoji: '📻',
    category: 'Andras appar',
    tags: ['FastAPI', 'React', 'ElevenLabs'],
    imageSeed: 'owl-creek-radio',
    status: 'active',
    createdAt: '2026-06-10T12:00:00Z',
    type: 'Web App',
    url: 'https://owlcreek.alexcloud.se',
  },
];

// Spel från Spelarkivet (games.alexcloud.se)
export const GAMES: AppDefinition[] = [
  {
    id: 'gangstad',
    bannerImage: 'https://gangstad.alexcloud.se/og.png',
    title: 'Gangstad',
    description: 'Top-down brottsspel i retrostil – kör, smit, slåss och klara uppdrag medan polisen jagar dig.',
    icon: '🚗',
    banner: "radial-gradient(circle at 40% 35%, rgba(255, 210, 63, 0.22), #0b0d13)",
    bannerEmoji: '🚗',
    category: 'Arkad',
    tags: ['Top-down', 'Action', 'PixiJS'],
    imageSeed: 'gangstad',
    status: 'active',
    createdAt: '2026-06-14T12:00:00Z',
    type: 'Game',
    url: 'https://gangstad.alexcloud.se',
  },
  {
    id: 'snake',
    bannerImage: 'https://databasen.alexcloud.se/assets/e0704307-d4b9-4a98-8bde-4f764527ccad?width=800&quality=80',
    title: 'Snake',
    description: 'Styr ormen, ät mat och undvik att krocka. Hur lång kan du bli?',
    icon: '🐍',
    banner: "radial-gradient(circle at 50% 50%, rgba(0, 245, 255, 0.25), #030009)",
    bannerEmoji: '🐍',
    category: 'Klassiker',
    tags: ['Arkad', 'Klassiker'],
    imageSeed: 'snake',
    status: 'active',
    createdAt: '2026-03-01T12:00:00Z',
    type: 'Game',
    url: 'https://games.alexcloud.se/Snake/',
  },
  {
    id: 'kodknackaren',
    bannerImage: 'https://databasen.alexcloud.se/assets/b8568489-1c2f-41b4-90a9-9d5b5042c822?width=800&quality=80',
    title: 'Kodknäckaren',
    description: 'Ta dig igenom 8 labyrintnivåer, lös gåtor och fly från fienden som jagar dig!',
    icon: '🧩',
    banner: "radial-gradient(circle at 30% 40%, rgba(191, 95, 255, 0.3), #030009)",
    bannerEmoji: '🧩',
    category: 'Pussel',
    tags: ['Labyrint', 'Gåtor'],
    imageSeed: 'kodknackaren',
    status: 'active',
    createdAt: '2026-03-15T12:00:00Z',
    type: 'Game',
    url: 'https://kodknackaren.alexcloud.se',
  },
  {
    id: 'solhem-escape',
    bannerImage: 'https://databasen.alexcloud.se/assets/5eab28c2-7aa1-45d2-bd0c-1c3a42c72b46?width=800&quality=80',
    title: 'Solhem Escape',
    description: 'Escape room i det gula huset Solhem. Klara 11 rum med kodutmaningar – ända fram till bastun och en kall öl!',
    icon: '🏠',
    banner: "linear-gradient(135deg, #FFD23F, #F4A300)",
    bannerEmoji: '🏠',
    category: 'Escape Room',
    tags: ['React', 'Vite', 'Pussel'],
    imageSeed: 'solhem-escape',
    status: 'active',
    createdAt: '2026-06-06T12:00:00Z',
    type: 'Game',
    url: 'https://kodaganget.alexcloud.se',
  },
  {
    id: 'bubble-bobble',
    bannerImage: 'https://databasen.alexcloud.se/assets/ce20b037-e2a0-4ddf-a7a1-b37b6a82a199?width=800&quality=80',
    title: 'Bubble Bobble',
    description: 'Fånga fiender i bubblor och poppa dem för poäng! Klassisk arkadaction med flera nivåer.',
    icon: '🫧',
    banner: "radial-gradient(circle at 50% 50%, rgba(255, 110, 216, 0.3), #030009)",
    bannerEmoji: '🫧',
    category: 'Arkad',
    tags: ['Arkad', 'Klassiker'],
    imageSeed: 'bubble-bobble',
    status: 'active',
    createdAt: '2026-04-21T12:00:00Z',
    type: 'Game',
    url: 'https://bubblebobble.alexcloud.se',
  },
  {
    id: 'trackfield',
    bannerImage: 'https://databasen.alexcloud.se/assets/a4320446-c156-42fc-96ca-bfbab2f445b3?width=800&quality=80',
    title: 'SpelTrackField',
    description: 'Fem friidrottsgrenar – 100 m, längdhopp, spjut, häcklöpning och diskus. Tävla mot rivalspöket!',
    icon: '🏃',
    banner: "radial-gradient(circle at 50% 50%, rgba(255, 200, 0, 0.25), #030009)",
    bannerEmoji: '🏃',
    category: 'Sport',
    tags: ['Friidrott', 'Arkad'],
    imageSeed: 'trackfield',
    status: 'active',
    createdAt: '2026-05-05T12:00:00Z',
    type: 'Game',
    url: 'https://trackfield.alexcloud.se',
  },
  {
    id: 'teckenspel',
    bannerImage: 'https://databasen.alexcloud.se/assets/6ffdae4f-e4ec-4202-9fea-7d7c861bb4cf?width=800&quality=80',
    title: 'Teckenspel',
    description: 'Lär dig teckenspråk med ett interaktivt brädspel – videofrågor, dueller och online-multiplayer!',
    icon: '🤟',
    banner: "linear-gradient(135deg, #3C2C85, #9EE7FF)",
    bannerEmoji: '🤟',
    category: 'Utbildning',
    tags: ['Next.js', 'Directus', 'Multiplayer'],
    imageSeed: 'teckenspel',
    status: 'active',
    createdAt: '2026-04-08T12:00:00Z',
    type: 'Game',
    url: 'https://teckenspel.alexcloud.se',
  },
  {
    id: 'retro-racer',
    bannerImage: 'https://databasen.alexcloud.se/assets/806155d9-8d46-4c43-bd4a-f176acdee248?width=800&quality=80',
    title: 'Retro Racer',
    description: 'Snabbt 8-bitars racingspel med synthwave-musik och pseudo-3D väg. Undvik trafiken!',
    icon: '🏎️',
    banner: "radial-gradient(circle at 50% 50%, rgba(255, 0, 255, 0.25), #030009)",
    bannerEmoji: '🏎️',
    category: 'Racing',
    tags: ['Canvas', 'Retro', 'Arkad'],
    imageSeed: 'retro-racer',
    status: 'active',
    createdAt: '2026-04-25T12:00:00Z',
    type: 'Game',
    url: 'https://retroracer.alexcloud.se',
  },
  {
    id: 'indianajones',
    bannerImage: 'https://databasen.alexcloud.se/assets/a28b6674-394c-408f-bb48-b0f58834fca0?width=800&quality=80',
    title: 'Indiana Jones',
    description: 'Äventyra genom djungel, tempel och grottor – lös sex listiga pussel och fly undan stenblocket i sista sekund.',
    icon: '🗿',
    banner: "radial-gradient(circle at 50% 50%, rgba(201, 162, 78, 0.3), #1a0a05)",
    bannerEmoji: '🗿',
    category: 'Äventyr',
    tags: ['Pussel', 'Äventyr'],
    imageSeed: 'indianajones',
    status: 'active',
    createdAt: '2026-05-08T12:00:00Z',
    type: 'Game',
    url: 'https://indianajones.alexcloud.se',
  },
  {
    id: 'risk',
    bannerImage: 'https://databasen.alexcloud.se/assets/f08c8234-f338-496a-ae23-0dd3b3f2e002?width=800&quality=80',
    title: 'Risk',
    description: 'Klassiskt världserövrings-brädspel – erövra kontinenter, slå dina motståndare och ta över världen.',
    icon: '⚔️',
    banner: "linear-gradient(135deg, #7b2d2d, #1a3a5c)",
    bannerEmoji: '⚔️',
    category: 'Strategi',
    tags: ['Brädspel', 'Strategi'],
    imageSeed: 'risk',
    status: 'active',
    createdAt: '2026-04-29T12:00:00Z',
    type: 'Game',
    url: 'https://risk.alexcloud.se',
  },
  {
    id: 'sjoslaget',
    bannerImage: 'https://databasen.alexcloud.se/assets/8c1de8a7-bc64-483a-b077-8f0053925e4f?width=800&quality=80',
    title: 'Sjöslaget',
    description: 'Klassiskt Battleship i realtid. Placera din flotta och sjunka motståndarens skepp!',
    icon: '🚢',
    banner: "linear-gradient(135deg, #0a1628, #1a4a8a)",
    bannerEmoji: '🚢',
    category: 'Strategi',
    tags: ['Multiplayer', 'Brädspel'],
    imageSeed: 'sjoslaget',
    status: 'active',
    createdAt: '2026-05-03T12:00:00Z',
    type: 'Game',
    url: 'https://sjoslaget.alexcloud.se',
  },
  {
    id: 'risk-ultimat',
    bannerImage: 'https://databasen.alexcloud.se/assets/f08c8234-f338-496a-ae23-0dd3b3f2e002?width=800&quality=80',
    title: 'Risk Ultimat',
    description: 'Erövra världen med arméer och flottor. Teknikträd, hemliga mål och dominionspoäng.',
    icon: '🌍',
    banner: "radial-gradient(circle at 50% 50%, rgba(139, 0, 0, 0.35), #0d0010)",
    bannerEmoji: '🌍',
    category: 'Strategi',
    tags: ['Brädspel', 'Strategi'],
    imageSeed: 'risk-ultimat',
    status: 'active',
    createdAt: '2026-05-20T12:00:00Z',
    type: 'Game',
    url: 'https://riskworld.alexcloud.se',
  },
];

// Appar från Appbiblioteket (alexcloud.se/apps.html)
export const APPS: AppDefinition[] = [
  {
    id: 'sommarplanerare',
    bannerImage: 'https://databasen.alexcloud.se/assets/6bf62901-4001-4bc8-b9e3-a7114b5ea7f6?width=800&quality=80',
    title: 'Sommarplanerare',
    description: 'Semesterplanering för sommaren 2026 – Prag, Grebbestad, hundvecka och golf som stora visuella kort med nedräkning, checklistor, packlistor, budget och resetips. Skapa egna aktiviteter med bildväljare och emoji.',
    icon: '☀️',
    banner: "linear-gradient(135deg, #0ea5e9, #2ec4b6)",
    bannerEmoji: '🏖️',
    category: 'Resor',
    tags: ['Node.js', 'Express', 'Vanilla JS'],
    imageSeed: 'sommarplanerare',
    status: 'active',
    createdAt: '2026-06-12T12:00:00Z',
    type: 'Web App',
    url: 'https://sommar.alexcloud.se',
  },
  {
    id: 'matrix-slim',
    bannerImage: 'https://databasen.alexcloud.se/assets/466f12e1-f4e6-4247-a784-a84a3c8b283f?width=800&quality=80',
    title: 'Matrix Slim',
    description: 'Receptsökning i cyberstil – välj vad du har i kylskåpet och få måltidsförslag från TheMealDB, automatiskt översatta till svenska med uppskattade kalorier och protein per portion.',
    icon: '🥗',
    banner: "linear-gradient(135deg, #0072ff, #00f0ff)",
    bannerEmoji: '🍽️',
    category: 'Mat',
    tags: ['Node.js', 'TheMealDB', 'LibreTranslate', 'Directus'],
    imageSeed: 'matrix-slim',
    status: 'active',
    createdAt: '2026-06-11T12:00:00Z',
    type: 'Web App',
    url: 'https://recept.alexcloud.se',
  },
  {
    id: 'cv-portfolio',
    bannerImage: 'https://databasen.alexcloud.se/assets/a3c351ba-f665-4e43-a643-3f05a36c8c68?width=800&quality=80',
    title: 'CV – Matrix Portfolio',
    description: 'Interaktivt CV i Matrix-stil. Välj det röda pillret för en 3D-upplevelse med flygintro, syntetiserad musik och AI-terminal – eller det vita för en avskalad textversion. CV genereras som PDF i realtid, på svenska och engelska.',
    icon: '🕶️',
    banner: "linear-gradient(135deg, #000000, #00ff66)",
    bannerEmoji: '💊',
    category: 'Företag',
    tags: ['Three.js', 'WebAudio', 'Node.js', 'pdfkit'],
    imageSeed: 'cv-portfolio',
    status: 'active',
    createdAt: '2026-06-11T12:00:00Z',
    type: 'Web App',
    url: 'https://cv.alexcloud.se',
  },
  {
    id: 'hemmaflode',
    bannerImage: 'https://databasen.alexcloud.se/assets/a138f167-e5d1-4d42-94ee-3ffb27e2515e?width=800&quality=80',
    title: 'Hemmaflöde',
    description: 'Streama dina egna filmer från servern till TV:n – som en privat Plex. Skannar mediamappar, stödjer undertexter, transkodning och casting till Chromecast.',
    icon: '📺',
    banner: "linear-gradient(135deg, #7f1d1d, #f5a623)",
    bannerEmoji: '🎬',
    category: 'Familj',
    tags: ['Node.js', 'Express', 'ffmpeg'],
    imageSeed: 'hemmaflode',
    status: 'active',
    createdAt: '2026-06-09T12:00:00Z',
    type: 'Web App',
    url: 'https://flode.alexcloud.se',
  },
  {
    id: 'coaster-tycoon',
    bannerImage: 'https://databasen.alexcloud.se/assets/97bdef9f-db3e-4b99-a49e-cf2e76ac6f5e?width=800&quality=80',
    title: 'Coaster Tycoon',
    description: 'Bygg din egen nöjespark i isometrisk 2D — forma terräng, lägg stigar, designa berg-och-dalbanor och se gästerna myllra runt. Spara dina parker online.',
    icon: '🎢',
    banner: "linear-gradient(135deg, #f59e0b, #ef4444)",
    bannerEmoji: '🎢',
    category: 'Kreativt',
    tags: ['React', 'Canvas 2D', 'Directus'],
    imageSeed: 'coaster-tycoon',
    status: 'active',
    createdAt: '2026-06-08T12:00:00Z',
    type: 'Web App',
    url: 'https://coaster.alexcloud.se',
  },
  {
    id: 'dovflode',
    bannerImage: 'https://databasen.alexcloud.se/assets/90a7df8d-842d-4df0-a87a-38c1051125d9?width=800&quality=80',
    title: 'Dövflöde',
    description: 'Nyhets- och händelsegalleri för dövvärlden i Sverige. Följ nyheter, evenemang, sport, kultur och föreningsliv från SDR, SDIF och lokala föreningar – i flöde och på interaktiv karta.',
    icon: '📰',
    banner: "linear-gradient(135deg, #1e6fd9, #14b8a6)",
    bannerEmoji: '🤟',
    category: 'Nyheter',
    tags: ['Next.js', 'Leaflet', 'Directus'],
    imageSeed: 'dovflode',
    status: 'active',
    createdAt: '2026-06-06T12:00:00Z',
    type: 'Web App',
    url: 'https://dovflode.alexcloud.se',
  },
  {
    id: 'solhem-escape',
    bannerImage: 'https://databasen.alexcloud.se/assets/5eab28c2-7aa1-45d2-bd0c-1c3a42c72b46?width=800&quality=80',
    title: 'Solhem Escape',
    description: 'Ett escape room-äventyr i det gula huset Solhem. Ta dig igenom 11 rum fyllda med kod- och teknikutmaningar – ända fram till bastun och en kall öl.',
    icon: '🍺',
    banner: "linear-gradient(135deg, #FFD23F, #F4A300)",
    bannerEmoji: '🏠',
    category: 'Utbildning',
    tags: ['React', 'Vite', 'Spel'],
    imageSeed: 'solhem-escape',
    status: 'active',
    createdAt: '2026-06-06T12:00:00Z',
    type: 'Web App',
    url: 'https://kodaganget.alexcloud.se',
  },
  {
    id: 'kalorikollen',
    bannerImage: 'https://databasen.alexcloud.se/assets/434fdead-07cd-45d8-af3d-289eae380576?width=800&quality=80',
    title: 'Kalorikollen',
    description: 'En smart app designad för att logga mat, räkna kalorier och hålla koll på nutritionen dagligen. Enkelt gränssnitt för att snabbt lägga till måltider.',
    icon: '🔥',
    banner: "linear-gradient(135deg, #FF6B6B, #556270)",
    bannerEmoji: '🥗',
    category: 'Hälsa',
    tags: ['React', 'Node.js'],
    imageSeed: 'kalorikollen',
    status: 'active',
    createdAt: '2026-03-10T12:00:00Z',
    type: 'Web App',
    url: 'https://kalorikollen.alexcloud.se/',
  },
  {
    id: 'hundvakt',
    bannerImage: 'https://databasen.alexcloud.se/assets/f93f9c00-2124-4cd4-a549-3b587acd9c4c?width=800&quality=80',
    title: 'Hundvakt CRM',
    description: 'Ett komplett boknings- och kundregister för hundvaktsverksamhet. Hantera nya hundar, kunder, incheckningar och kalender direkt från mobilen.',
    icon: '🐾',
    banner: "url('https://minio.alexcloud.se/public-assets/hundvakt.jpeg') center / cover no-repeat",
    bannerEmoji: '',
    category: 'Företag',
    tags: ['Vite', 'Firebase'],
    imageSeed: 'hundvakt',
    status: 'active',
    createdAt: '2026-02-23T12:00:00Z',
    type: 'Web App',
    url: 'https://hundvakt.alexcloud.se',
  },
  {
    id: 'surd',
    bannerImage: 'https://databasen.alexcloud.se/assets/5a8872a7-f82d-4cea-8252-ea877f0fbd1e?width=800&quality=80',
    title: 'IK Surd Padel',
    description: 'Padel-app för IK Surds padelsektionen. Träningar, tävlingar, matchbokning, forum och AI-coach — allt på ett ställe.',
    icon: '🏆',
    banner: "linear-gradient(135deg, #1a2fa0, #c9a84c)",
    bannerEmoji: '🎾',
    category: 'Sport',
    tags: ['Supabase', 'PWA'],
    imageSeed: 'surd-padel',
    status: 'active',
    createdAt: '2026-03-15T12:00:00Z',
    type: 'PWA',
    url: 'https://padelsurd.alexcloud.se',
  },
  {
    id: 'larareai',
    bannerImage: 'https://databasen.alexcloud.se/assets/f1210e60-b28a-40b8-94a7-261e5578f33f?width=800&quality=80',
    title: 'LärareAI',
    description: 'En AI-driven lärarapp som hjälper elever och lärare med undervisning, frågor och pedagogiskt stöd. Smart, personlig och tillgänglig dygnet runt.',
    icon: '🤖',
    banner: "linear-gradient(135deg, #f7971e, #ffd200)",
    bannerEmoji: '📚',
    category: 'Utbildning',
    tags: ['Claude AI', 'Web App'],
    imageSeed: 'larareai',
    status: 'active',
    createdAt: '2026-03-11T12:00:00Z',
    type: 'Web App',
    url: 'https://larareai.alexcloud.se/',
  },
  {
    id: 'filmtextning',
    bannerImage: 'https://databasen.alexcloud.se/assets/cca10ac0-4009-40c2-990b-d6364aa55eaa?width=800&quality=80',
    title: 'Filmtextning',
    description: 'AI-driven app för att skapa textremsor till videor. Automatisk transkribering med OpenAI Whisper, översättning till flera språk och export som SRT-filer.',
    icon: '🎤',
    banner: "linear-gradient(135deg, #667eea, #764ba2)",
    bannerEmoji: '🎬',
    category: 'Kreativt',
    tags: ['OpenAI Whisper', 'Claude AI'],
    imageSeed: 'filmtextning',
    status: 'active',
    createdAt: '2026-03-14T12:00:00Z',
    type: 'Web App',
    url: 'https://filmtext.alexcloud.se',
  },
  {
    id: 'musikverkstan',
    bannerImage: 'https://databasen.alexcloud.se/assets/c7e155d5-6740-47e5-94e0-05e2fa9b7862?width=800&quality=80',
    title: 'Musikverkstan',
    description: 'AI-musikstudio för att skriva texter, generera musik, lägga till röst och skapa omslag i ett och samma projekt.',
    icon: '🎼',
    banner: "linear-gradient(135deg, #7c3aed, #06b6d4)",
    bannerEmoji: '🎵',
    category: 'Kreativt',
    tags: ['Next.js', 'OpenAI', 'Suno'],
    imageSeed: 'musikverkstan',
    status: 'active',
    createdAt: '2026-03-13T12:00:00Z',
    type: 'Web App',
    url: 'https://musikappen.alexcloud.se',
  },
  {
    id: 'rabiff',
    bannerImage: 'https://databasen.alexcloud.se/assets/334737bd-7990-42f0-9c60-d8de89a3179b?width=800&quality=80',
    title: 'Råbiff-rankingen',
    description: 'Betygsätt och håll koll på dina bästa råbiffar. Lägg till bilder, plats och poäng — se alla betyg på karta eller i grid.',
    icon: '⭐',
    banner: "linear-gradient(135deg, #8B4513, #D2691E)",
    bannerEmoji: '🥩',
    category: 'Mat',
    tags: ['React', 'Directus', 'PWA'],
    imageSeed: 'rabiff',
    status: 'active',
    createdAt: '2026-02-26T12:00:00Z',
    type: 'PWA',
    url: 'http://rabiffen.alexcloud.se',
  },
  {
    id: 'golfapp2',
    bannerImage: 'https://databasen.alexcloud.se/assets/bde64d80-4991-4c16-8c24-97b2c91244e1?width=800&quality=80',
    title: 'Golfapp 2.0',
    description: 'Spåra golfrundor, hantera din bag, beräkna handikapp och se din utveckling över tid.',
    icon: '🏌️',
    banner: "linear-gradient(135deg, #0D2818, #1a5c34)",
    bannerEmoji: '⛳',
    category: 'Sport',
    tags: ['React', 'Directus', 'PWA'],
    imageSeed: 'golfapp2',
    status: 'active',
    createdAt: '2026-03-12T12:00:00Z',
    type: 'PWA',
    url: 'https://golfapp2.alexcloud.se',
  },
  {
    id: 'padel-dashboard',
    bannerImage: 'https://databasen.alexcloud.se/assets/5a8872a7-f82d-4cea-8252-ea877f0fbd1e?width=800&quality=80',
    title: 'Padel-Dashboard',
    description: 'Personlig padel-app. Logga matcher med vinn/förlust, hantera racket, kör Americano & Mexicano-turneringar och få personliga AI-coachningstips från Claude.',
    icon: '🎾',
    banner: "linear-gradient(135deg, #070d1a, #163312)",
    bannerEmoji: '🏓',
    category: 'Sport',
    tags: ['React', 'Claude AI', 'Directus', 'PWA'],
    imageSeed: 'padel-dashboard',
    status: 'active',
    createdAt: '2026-03-16T12:00:00Z',
    type: 'PWA',
    url: 'https://padeltraning.alexcloud.se',
  },
  {
    id: 'balansa',
    bannerImage: 'https://databasen.alexcloud.se/assets/a273d9e8-a725-456c-9a95-a574c1f3b0a6?width=800&quality=80',
    title: 'Balansa',
    description: 'Personlig budget-app. Registrera inkomster och utgifter per kategori, sätt sparmål och följ din månadsbudget i realtid.',
    icon: '📊',
    banner: "linear-gradient(135deg, #064e3b, #065f46)",
    bannerEmoji: '💰',
    category: 'Ekonomi',
    tags: ['React', 'Directus'],
    imageSeed: 'balansa',
    status: 'active',
    createdAt: '2026-03-17T12:00:00Z',
    type: 'Web App',
    url: 'https://budget.alexcloud.se',
  },
  {
    id: 'jarl',
    bannerImage: 'https://databasen.alexcloud.se/assets/ad0c3ba7-fe30-4e29-a40d-d888882e7988?width=800&quality=80',
    title: 'Jarl',
    description: 'En föräldrarapp med uppmuntran till sina barn.',
    icon: '⭐',
    banner: "linear-gradient(135deg, #ff9a9e, #fecfef)",
    bannerEmoji: '👨‍👩‍👧‍👦',
    category: 'Familj',
    tags: ['Web App'],
    imageSeed: 'jarl',
    status: 'active',
    createdAt: '2026-03-08T12:00:00Z',
    type: 'Web App',
    url: 'https://jarl.alexcloud.se/',
  },
  {
    id: 'bilkostnad',
    bannerImage: 'https://databasen.alexcloud.se/assets/3728dcfa-2b34-4015-95ce-399d33405e98?width=800&quality=80',
    title: 'Bilkostnad',
    description: 'Håll koll på alla bilkostnader – bränsle, service, lagning, försäkring, trängselskatt och besiktning. HUD-design med bränslemätare, månadsgraf och påminnelser.',
    icon: '⛽',
    banner: "linear-gradient(135deg, #030c18, #0a2a4a)",
    bannerEmoji: '🚗',
    category: 'Ekonomi',
    tags: ['React', 'Directus', 'PWA'],
    imageSeed: 'bilkostnad',
    status: 'active',
    createdAt: '2026-03-19T12:00:00Z',
    type: 'PWA',
    url: 'https://bil.alexcloud.se',
  },
  {
    id: 'teckensprakai',
    bannerImage: 'https://databasen.alexcloud.se/assets/6ffdae4f-e4ec-4202-9fea-7d7c861bb4cf?width=800&quality=80',
    title: 'Teckenspråks AI',
    description: 'AI-drivet klassrum för teckenspråk. Interaktiva lektioner med AI-stöd som hjälper elever lära sig teckenspråk i sin egen takt.',
    icon: '💬',
    banner: "linear-gradient(135deg, #134e5e, #71b280)",
    bannerEmoji: '🤟',
    category: 'Utbildning',
    tags: ['Node.js', 'OpenAI'],
    imageSeed: 'teckensprakai',
    status: 'active',
    createdAt: '2026-03-08T12:00:00Z',
    type: 'Web App',
    url: 'https://teckensprak.alexcloud.se',
  },
  {
    id: 'pragguiden',
    bannerImage: 'https://databasen.alexcloud.se/assets/76d8387f-6760-42d8-bd27-31a3c8835fca?width=800&quality=80',
    title: 'Pragguiden',
    description: 'Reseguide och delad reseplanerare för Prag. Planera dag för dag med aktiviteter, budget och anteckningar — synkat i realtid med din reskamrat.',
    icon: '✈️',
    banner: "linear-gradient(135deg, #0D0C0A, #2E2A24)",
    bannerEmoji: '🏰',
    category: 'Resor',
    tags: ['Node.js', 'Directus', 'PWA'],
    imageSeed: 'pragguiden',
    status: 'active',
    createdAt: '2026-03-30T12:00:00Z',
    type: 'PWA',
    url: 'https://pragguiden.alexcloud.se',
  },
  {
    id: 'borrby',
    bannerImage: 'https://databasen.alexcloud.se/assets/81c0cfd7-9e45-4d8c-84a3-ea23071ca6ad?width=800&quality=80',
    title: 'Reseguide Borrby',
    description: 'Premium reseapp för Borrby & Österlen. Utforska natur, golf, fika och dagsutflykter i Skånes vackraste hörn.',
    icon: '🏌️',
    banner: "linear-gradient(135deg, #6b8f71, #8fbf8f)",
    bannerEmoji: '🌿',
    category: 'Resor',
    tags: ['React', 'Vite', 'Framer Motion'],
    imageSeed: 'borrby',
    status: 'active',
    createdAt: '2026-03-30T12:00:00Z',
    type: 'Web App',
    url: 'https://borrby.alexcloud.se',
  },
  {
    id: 'teckenresan-multiplayer',
    bannerImage: 'https://databasen.alexcloud.se/assets/90a7df8d-842d-4df0-a87a-38c1051125d9?width=800&quality=80',
    title: 'Teckenresan',
    description: 'Interaktivt teckenspråksspel med online-multiplayer via Firebase.',
    icon: '🖐️',
    banner: "linear-gradient(135deg, #4a90d9, #7b2ff7)",
    bannerEmoji: '🤟',
    category: 'Utbildning',
    tags: ['React', 'Vite', 'Firebase'],
    imageSeed: 'teckenresan-multiplayer',
    status: 'active',
    createdAt: '2026-04-06T12:00:00Z',
    type: 'Web App',
    url: 'https://teckenresan.alexcloud.se',
  },
  {
    id: 'teckenspel',
    bannerImage: 'https://databasen.alexcloud.se/assets/6ffdae4f-e4ec-4202-9fea-7d7c861bb4cf?width=800&quality=80',
    title: 'Teckenspel',
    description: 'Ett interaktivt brädspel för att lära sig teckenspråk med vänner – med videofrågor och online-multiplayer.',
    icon: '🎮',
    banner: "linear-gradient(135deg, #3C2C85, #9EE7FF)",
    bannerEmoji: '🤟',
    category: 'Utbildning',
    tags: ['Next.js', 'Directus'],
    imageSeed: 'teckenspel-app',
    status: 'active',
    createdAt: '2026-04-08T12:00:00Z',
    type: 'Web App',
    url: 'https://teckenspel.alexcloud.se',
  },
  {
    id: 'vmtips',
    bannerImage: 'https://databasen.alexcloud.se/assets/d7167c68-6563-44fc-ba5b-d97cc80208e3?width=800&quality=80',
    title: 'VMtips 2026',
    description: 'Tipsa om VM-matcher i fotboll 2026. Gruppspel, slutspel, skyttekung och mästare. Tävla mot vänner och följ ligatabellen live.',
    icon: '⚽',
    banner: "linear-gradient(135deg, #041610, #0a3d20)",
    bannerEmoji: '🏆',
    category: 'Sport',
    tags: ['Next.js', 'Directus', 'Google Auth'],
    imageSeed: 'vmtips',
    status: 'active',
    createdAt: '2026-04-09T12:00:00Z',
    type: 'Web App',
    url: 'https://vmtips.alexcloud.se',
  },
  {
    id: 'golfvanner',
    bannerImage: 'https://databasen.alexcloud.se/assets/c0940777-818c-4473-830e-7237622ead91?width=800&quality=80',
    title: 'Golfvänner',
    description: 'Hitta spelpartners, boka ronder och samåk till banan i Göteborg.',
    icon: '🏌️',
    banner: "linear-gradient(135deg, #2d5a27, #4a8f3f)",
    bannerEmoji: '⛳',
    category: 'Sport',
    tags: ['Next.js', 'Directus', 'Leaflet'],
    imageSeed: 'golfvanner',
    status: 'active',
    createdAt: '2026-04-11T12:00:00Z',
    type: 'Web App',
    url: 'https://golfvanner.alexcloud.se',
  },
  {
    id: 'teckenresan-bradspel',
    bannerImage: 'https://databasen.alexcloud.se/assets/90a7df8d-842d-4df0-a87a-38c1051125d9?width=800&quality=80',
    title: 'Teckenresan',
    description: 'Interaktivt brädspel för att lära sig teckenspråk. Spela lokalt eller online med vänner genom 4 olika världar – Djur, Familj, Mat och Siffror.',
    icon: '🎲',
    banner: "linear-gradient(135deg, #1a1a2e, #16213e, #0f3460)",
    bannerEmoji: '🤟',
    category: 'Utbildning',
    tags: ['Next.js', 'Directus', 'TypeScript'],
    imageSeed: 'teckenresan-bradspel',
    status: 'active',
    createdAt: '2026-04-13T12:00:00Z',
    type: 'Web App',
    url: 'https://teckenresan.alexcloud.se',
  },
  {
    id: 'rabiffjakten',
    bannerImage: 'https://databasen.alexcloud.se/assets/334737bd-7990-42f0-9c60-d8de89a3179b?width=800&quality=80',
    title: 'Råbiffjakten',
    description: 'Rankning av Göteborgs bästa råbiffar – med betyg, smaknotes och karta.',
    icon: '🔪',
    banner: "linear-gradient(135deg, #3D1A00, #8B3A00)",
    bannerEmoji: '🥩',
    category: 'Mat',
    tags: ['Expo', 'React Native', 'TypeScript'],
    imageSeed: 'rabiffjakten',
    status: 'active',
    createdAt: '2026-04-19T12:00:00Z',
    type: 'Mobile App',
    url: 'https://rabiffjakten.alexcloud.se',
  },
  {
    id: 'videostudio',
    bannerImage: 'https://databasen.alexcloud.se/assets/4d952993-0b27-4c58-b758-d741c8be3e30?width=800&quality=80',
    title: 'Video Studio',
    description: 'Skapa och redigera videor med stilfulla bakgrunder och teman.',
    icon: '🎥',
    banner: "linear-gradient(135deg, #1a1a2e, #e94560)",
    bannerEmoji: '🎬',
    category: 'Kreativt',
    tags: ['Next.js', 'TypeScript'],
    imageSeed: 'videostudio',
    status: 'active',
    createdAt: '2026-04-23T12:00:00Z',
    type: 'Web App',
    url: 'https://videostudio.alexcloud.se',
  },
  {
    id: 'aura',
    bannerImage: 'https://databasen.alexcloud.se/assets/e399b32f-9c36-4749-a091-b5b3c7cbe463?width=800&quality=80',
    title: 'Aura',
    description: 'En personlig fristad för fokus, meditation och sömnoptimering.',
    icon: '✨',
    banner: "linear-gradient(135deg, #061b0e, #50625c)",
    bannerEmoji: '🧘',
    category: 'Hälsa',
    tags: ['React', 'TypeScript', 'Gemini AI'],
    imageSeed: 'aura',
    status: 'active',
    createdAt: '2026-04-23T12:00:00Z',
    type: 'Web App',
    url: 'https://aura.alexcloud.se',
  },
  {
    id: 'rakpriset',
    bannerImage: 'https://databasen.alexcloud.se/assets/cdc50138-9099-44f5-a4ec-e22e52d2a889?width=800&quality=80',
    title: 'Räkpriset',
    description: 'Jämför dagspriser på räkor hos fiskhandlare och matbutiker i Göteborg.',
    icon: '💰',
    banner: "linear-gradient(135deg, #0e2d45, #2d7da8)",
    bannerEmoji: '🦐',
    category: 'Mat',
    tags: ['Next.js', 'TypeScript', 'Directus'],
    imageSeed: 'rakpriset',
    status: 'active',
    createdAt: '2026-04-24T12:00:00Z',
    type: 'Web App',
    url: 'https://rakpriser.alexcloud.se',
  },
  {
    id: 'risk',
    bannerImage: 'https://databasen.alexcloud.se/assets/f08c8234-f338-496a-ae23-0dd3b3f2e002?width=800&quality=80',
    title: 'Risk',
    description: 'Klassiskt världserövrings-brädspel mot tre AI-motståndare.',
    icon: '🌍',
    banner: "linear-gradient(135deg, #7b2d2d, #1a3a5c)",
    bannerEmoji: '⚔️',
    category: 'Familj',
    tags: ['React', 'Vite', 'Node.js'],
    imageSeed: 'risk-app',
    status: 'active',
    createdAt: '2026-04-29T12:00:00Z',
    type: 'Web App',
    url: 'https://risk.alexcloud.se',
  },
  {
    id: 'sjoslaget',
    bannerImage: 'https://databasen.alexcloud.se/assets/8c1de8a7-bc64-483a-b077-8f0053925e4f?width=800&quality=80',
    title: 'Sjöslaget',
    description: 'Klassiskt Battleship för två spelare i realtid. Dela rumskod och sjunka motståndarens flotta!',
    icon: '⚓',
    banner: "linear-gradient(135deg, #0a1628, #1a4a8a)",
    bannerEmoji: '🚢',
    category: 'Familj',
    tags: ['React', 'Vite', 'TypeScript', 'Directus'],
    imageSeed: 'sjoslaget-app',
    status: 'active',
    createdAt: '2026-05-03T12:00:00Z',
    type: 'Web App',
    url: 'https://sjoslaget.alexcloud.se',
  },
  {
    id: 'golfiq',
    bannerImage: 'https://databasen.alexcloud.se/assets/644985e0-82f7-4890-9eac-ef03b42709f9?width=800&quality=80',
    title: 'GolfIQ',
    description: 'Premium golf-statistikapp med handicaptrend, slag-för-slag-registrering, klubbhantering och AI-insikter.',
    icon: '🏌️',
    banner: "linear-gradient(135deg, #0B0F19, #064E3B)",
    bannerEmoji: '⛳',
    category: 'Sport',
    tags: ['React', 'Directus', 'PWA', 'Recharts'],
    imageSeed: 'golfiq',
    status: 'active',
    createdAt: '2026-05-10T12:00:00Z',
    type: 'PWA',
    url: 'https://golfiq.alexcloud.se',
  },
  {
    id: 'golftraning',
    bannerImage: 'https://databasen.alexcloud.se/assets/c0940777-818c-4473-830e-7237622ead91?width=800&quality=80',
    title: 'GolfTräning',
    description: 'SwingNotes – golf training journal med AI-tränare som ger personlig coaching på svenska.',
    icon: '🏌️',
    banner: "linear-gradient(135deg, #2D4A2D, #B8973A)",
    bannerEmoji: '⛳',
    category: 'Sport',
    tags: ['React', 'Node.js', 'AI'],
    imageSeed: 'golftraning',
    status: 'active',
    createdAt: '2026-05-12T12:00:00Z',
    type: 'Web App',
    url: 'https://golftraning.alexcloud.se',
  },
  {
    id: 'akagarden',
    bannerImage: 'https://databasen.alexcloud.se/assets/bde64d80-4991-4c16-8c24-97b2c91244e1?width=800&quality=80',
    title: 'Åkagårdens Golfguide',
    description: 'Hål-för-hål strategi och klubbguide för Åkagårdens GK.',
    icon: '🏌️',
    banner: "linear-gradient(135deg, #1a4a2e, #34c759)",
    bannerEmoji: '⛳',
    category: 'Sport',
    tags: ['React', 'Golf'],
    imageSeed: 'akagarden',
    status: 'active',
    createdAt: '2026-05-14T12:00:00Z',
    type: 'Web App',
    url: 'https://akagarden.alexcloud.se',
  },
  {
    id: 'caddie',
    bannerImage: 'https://databasen.alexcloud.se/assets/644985e0-82f7-4890-9eac-ef03b42709f9?width=800&quality=80',
    title: 'Caddie',
    description: 'Personlig golf-caddie med slagplaner hål för hål baserade på dina egna klubbdistanser.',
    icon: '⛳',
    banner: "linear-gradient(135deg, #10271c, #2d6a4f)",
    bannerEmoji: '🎯',
    category: 'Sport',
    tags: ['Next.js', 'Golf'],
    imageSeed: 'caddie',
    status: 'active',
    createdAt: '2026-05-28T12:00:00Z',
    type: 'Web App',
    url: 'https://caddieapp.alexcloud.se',
  },
  {
    id: 'seriekollen',
    bannerImage: 'https://databasen.alexcloud.se/assets/5b95443c-f828-4038-ad72-cda0f7d6c918?width=800&quality=80',
    title: 'Seriekollen',
    description: 'Håll koll på filmer och serier du ser på olika streamingtjänster. Betygsätt, sortera och sök med AI – allt på ett ställe.',
    icon: '📺',
    banner: "linear-gradient(135deg, #1a1a2e, #6c3483)",
    bannerEmoji: '🎬',
    category: 'Kreativt',
    tags: ['React', 'Claude AI'],
    imageSeed: 'seriekollen',
    status: 'active',
    createdAt: '2026-05-26T12:00:00Z',
    type: 'Web App',
    url: 'https://seriekollen.alexcloud.se',
  },
  {
    id: 'fairway',
    bannerImage: 'https://databasen.alexcloud.se/assets/bde64d80-4991-4c16-8c24-97b2c91244e1?width=800&quality=80',
    title: 'Fairway',
    description: 'Ladda upp FIT-filer från Garmin S20 och analysera din golfrunda hål för hål – scorecard, statistik, trender och hålanalys.',
    icon: '🏌️',
    banner: "linear-gradient(135deg, #1a2e1a, #3d6b47)",
    bannerEmoji: '⛳',
    category: 'Sport',
    tags: ['Next.js', 'Golf', 'Garmin'],
    imageSeed: 'fairway',
    status: 'active',
    createdAt: '2026-06-01T12:00:00Z',
    type: 'Web App',
    url: 'https://golfgps.alexcloud.se',
  },
];
